import Foundation

public enum SymptomCatalog {
    public static let symptoms: [CatalogItem] = [
        .init(id: "cramps", title: "Cramps", category: "Symptoms", sfSymbol: "bolt.heart"),
        .init(id: "headache", title: "Headache", category: "Symptoms", sfSymbol: "brain.head.profile"),
        .init(id: "backache", title: "Backache", category: "Symptoms", sfSymbol: "figure.stand"),
        .init(id: "breast_tenderness", title: "Breast tenderness", category: "Symptoms", sfSymbol: "heart"),
        .init(id: "bloating", title: "Bloating", category: "Symptoms", sfSymbol: "circle.grid.cross"),
        .init(id: "acne", title: "Acne", category: "Skin", sfSymbol: "face.smiling"),
        .init(id: "fatigue", title: "Fatigue", category: "Energy", sfSymbol: "battery.25"),
        .init(id: "insomnia", title: "Insomnia", category: "Sleep", sfSymbol: "moon.zzz"),
        .init(id: "nausea", title: "Nausea", category: "Digestion", sfSymbol: "cross.case"),
        .init(id: "constipation", title: "Constipation", category: "Digestion", sfSymbol: "leaf"),
        .init(id: "diarrhea", title: "Diarrhea", category: "Digestion", sfSymbol: "drop"),
        .init(id: "appetite_up", title: "Higher appetite", category: "Digestion", sfSymbol: "fork.knife"),
        .init(id: "appetite_down", title: "Lower appetite", category: "Digestion", sfSymbol: "fork.knife"),
        .init(id: "cravings", title: "Cravings", category: "Digestion", sfSymbol: "carrot"),
        .init(id: "dizziness", title: "Dizziness", category: "Symptoms", sfSymbol: "tornado"),
        .init(id: "hot_flashes", title: "Hot flashes", category: "Symptoms", sfSymbol: "thermometer.sun"),
        .init(id: "night_sweats", title: "Night sweats", category: "Sleep", sfSymbol: "drop.fill"),
        .init(id: "joint_pain", title: "Joint pain", category: "Symptoms", sfSymbol: "figure.walk"),
        .init(id: "pelvic_pain", title: "Pelvic pain", category: "Symptoms", sfSymbol: "cross.case"),
        .init(id: "ovulation_pain", title: "Ovulation pain", category: "Symptoms", sfSymbol: "waveform.path.ecg"),
        .init(id: "body_aches", title: "Body aches", category: "Symptoms", sfSymbol: "figure.flexibility"),
        .init(id: "chills", title: "Chills", category: "Symptoms", sfSymbol: "snowflake"),
        .init(id: "feverish", title: "Feverish", category: "Symptoms", sfSymbol: "thermometer"),
        .init(id: "allergies", title: "Allergies", category: "Symptoms", sfSymbol: "aqi.medium"),
        .init(id: "cold_flu", title: "Cold / flu feelings", category: "Symptoms", sfSymbol: "thermometer"),
        .init(id: "uti_symptoms", title: "UTI-like symptoms", category: "Symptoms", sfSymbol: "cross"),
        .init(id: "yeast_symptoms", title: "Yeast-like symptoms", category: "Symptoms", sfSymbol: "cross.circle"),
        .init(id: "dry_skin", title: "Dry skin", category: "Skin", sfSymbol: "hand.raised"),
        .init(id: "oily_skin", title: "Oily skin", category: "Skin", sfSymbol: "drop.circle"),
        .init(id: "hair_loss", title: "Hair shedding", category: "Skin", sfSymbol: "comb"),
        .init(id: "hair_growth", title: "Extra hair growth", category: "Skin", sfSymbol: "leaf.arrow.triangle.circlepath"),
        .init(id: "swelling", title: "Swelling", category: "Symptoms", sfSymbol: "circle.fill"),
        .init(id: "gas", title: "Gas", category: "Digestion", sfSymbol: "wind"),
        .init(id: "heartburn", title: "Heartburn", category: "Digestion", sfSymbol: "flame"),
        .init(id: "food_sensitivity", title: "Food sensitivity", category: "Digestion", sfSymbol: "exclamationmark.triangle"),
        .init(id: "libido_high", title: "Higher libido", category: "Sex", sfSymbol: "heart.circle"),
        .init(id: "libido_low", title: "Lower libido", category: "Sex", sfSymbol: "heart.slash"),
        .init(id: "sex_protected", title: "Protected sex", category: "Sex", sfSymbol: "checkmark.shield"),
        .init(id: "sex_unprotected", title: "Unprotected sex", category: "Sex", sfSymbol: "shield.slash"),
        .init(id: "orgasm", title: "Orgasm", category: "Sex", sfSymbol: "sparkle"),
        .init(id: "masturbation", title: "Masturbation", category: "Sex", sfSymbol: "hand.point.up"),
        .init(id: "discharge_creamy", title: "Creamy discharge", category: "Discharge", sfSymbol: "circle.dotted"),
        .init(id: "discharge_watery", title: "Watery discharge", category: "Discharge", sfSymbol: "humidity"),
        .init(id: "discharge_sticky", title: "Sticky discharge", category: "Discharge", sfSymbol: "circle.hexagongrid"),
        .init(id: "discharge_eggwhite", title: "Eggwhite discharge", category: "Discharge", sfSymbol: "circle.circle"),
        .init(id: "discharge_unusual", title: "Unusual discharge", category: "Discharge", sfSymbol: "exclamationmark.circle"),
        .init(id: "spotting_note", title: "Spotting noted", category: "Flow", sfSymbol: "drop"),
        .init(id: "clots", title: "Clots", category: "Flow", sfSymbol: "circle.grid.3x3"),
        .init(id: "exercise", title: "Exercised", category: "Lifestyle", sfSymbol: "figure.run"),
        .init(id: "meditation", title: "Meditation", category: "Lifestyle", sfSymbol: "brain"),
        .init(id: "travel", title: "Travel", category: "Lifestyle", sfSymbol: "airplane"),
        .init(id: "alcohol", title: "Alcohol", category: "Lifestyle", sfSymbol: "wineglass"),
        .init(id: "caffeine_high", title: "Lots of caffeine", category: "Lifestyle", sfSymbol: "cup.and.saucer"),
        .init(id: "stress_high", title: "High stress", category: "Lifestyle", sfSymbol: "cloud.bolt"),
        .init(id: "sick", title: "Felt sick", category: "Lifestyle", sfSymbol: "cross.circle"),
        .init(id: "medication", title: "Took medication", category: "Lifestyle", sfSymbol: "pills"),
        .init(id: "supplements", title: "Supplements", category: "Lifestyle", sfSymbol: "leaf.circle"),
        .init(id: "hydration_low", title: "Low hydration", category: "Lifestyle", sfSymbol: "drop.triangle"),
        .init(id: "good_sleep", title: "Good sleep", category: "Sleep", sfSymbol: "bed.double"),
        .init(id: "bad_sleep", title: "Poor sleep", category: "Sleep", sfSymbol: "bed.double.fill"),
        .init(id: "vivid_dreams", title: "Vivid dreams", category: "Sleep", sfSymbol: "moon.stars"),
        .init(id: "brain_fog", title: "Brain fog", category: "Energy", sfSymbol: "cloud.fog"),
        .init(id: "focus_high", title: "High focus", category: "Energy", sfSymbol: "scope"),
        .init(id: "energy_high", title: "High energy", category: "Energy", sfSymbol: "bolt"),
        .init(id: "energy_low", title: "Low energy", category: "Energy", sfSymbol: "bolt.slash"),
        .init(id: "social", title: "Social", category: "Lifestyle", sfSymbol: "person.3"),
        .init(id: "conflict", title: "Conflict", category: "Lifestyle", sfSymbol: "bubble.left.and.exclamationmark.bubble.right"),
        .init(id: "work_heavy", title: "Heavy workday", category: "Lifestyle", sfSymbol: "briefcase"),
        .init(id: "stretching", title: "Stretching / yoga", category: "Lifestyle", sfSymbol: "figure.cooldown"),
        .init(id: "pregnancy_test_neg", title: "Pregnancy test −", category: "TTC", sfSymbol: "minus.circle"),
        .init(id: "pregnancy_test_pos", title: "Pregnancy test +", category: "TTC", sfSymbol: "plus.circle"),
        .init(id: "lh_surge", title: "LH surge", category: "TTC", sfSymbol: "chart.line.uptrend.xyaxis"),
        .init(id: "bbt_logged", title: "BBT logged", category: "TTC", sfSymbol: "thermometer.medium")
    ]

    public static let moods: [CatalogItem] = [
        .init(id: "mood_happy", title: "Happy", category: "Mood", sfSymbol: "face.smiling"),
        .init(id: "mood_calm", title: "Calm", category: "Mood", sfSymbol: "leaf"),
        .init(id: "mood_sad", title: "Sad", category: "Mood", sfSymbol: "cloud.rain"),
        .init(id: "mood_anxious", title: "Anxious", category: "Mood", sfSymbol: "waveform.path"),
        .init(id: "mood_irritable", title: "Irritable", category: "Mood", sfSymbol: "flame"),
        .init(id: "mood_sensitive", title: "Sensitive", category: "Mood", sfSymbol: "heart"),
        .init(id: "mood_confident", title: "Confident", category: "Mood", sfSymbol: "star"),
        .init(id: "mood_apathetic", title: "Apathetic", category: "Mood", sfSymbol: "minus"),
        .init(id: "mood_angry", title: "Angry", category: "Mood", sfSymbol: "exclamationmark.triangle"),
        .init(id: "mood_grateful", title: "Grateful", category: "Mood", sfSymbol: "gift"),
        .init(id: "mood_lonely", title: "Lonely", category: "Mood", sfSymbol: "person"),
        .init(id: "mood_overwhelmed", title: "Overwhelmed", category: "Mood", sfSymbol: "hurricane")
    ]

    public static var allCount: Int { symptoms.count + moods.count }
}
